import type { RoomStage } from "@/types";

export const roomStages: RoomStage[] = [
  {
    id: "space",
    start: 0,
    end: 0.12,
    label: "01 / 06",
    text: "Сначала — пространство.",
    side: "left",
    objects: ["RoomShell", "ConcreteWalls", "FloorRaw"],
  },
  {
    id: "architecture",
    start: 0.12,
    end: 0.25,
    label: "02 / 06",
    text: "Мы выстраиваем архитектуру будущего интерьера.",
    side: "right",
    objects: ["FinishedWalls", "FloorFinished", "Ceiling", "Panels"],
  },
  {
    id: "lighting",
    start: 0.25,
    end: 0.4,
    label: "03 / 06",
    text: "Свет меняет не только комнату. Он меняет ощущение от нее.",
    side: "left",
    objects: ["Lighting", "Curtains"],
  },
  {
    id: "furniture",
    start: 0.4,
    end: 0.58,
    label: "04 / 06",
    text: "Каждый предмет занимает свое точное место.",
    side: "right",
    objects: ["Sofa", "Armchair", "CoffeeTable", "Rug"],
  },
  {
    id: "details",
    start: 0.58,
    end: 0.72,
    label: "05 / 06",
    text: "Детали создают характер.",
    side: "left",
    objects: ["Plants", "Decor", "Textiles"],
  },
  {
    id: "final",
    start: 0.72,
    end: 1,
    label: "06 / 06",
    text: "Пространство, в котором хочется остаться.",
    subtext: "От первой идеи до последнего предмета декора.",
    side: "right",
    objects: ["FinalLight"],
  },
];
