import type { Project } from "@/types";

const gallery = () => Array.from({ length: 6 }, () => "/images/interior-placeholder.svg");

export const projects: Project[] = [
  {
    slug: "quiet-harbor",
    title: "Тихая гавань",
    city: "Москва",
    area: "86 м²",
    year: "2026",
    type: "Квартира",
    description: "Спокойный интерьер для семьи, где хранение, свет и мягкие фактуры работают на ощущение тишины.",
    works: ["планировка", "3D-визуализация", "рабочая документация", "комплектация"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "3 комнаты", style: "теплый минимализм", palette: "taupe, камень, молочный" },
  },
  {
    slug: "soft-minimalism",
    title: "Мягкий минимализм",
    city: "Санкт-Петербург",
    area: "124 м²",
    year: "2025",
    type: "Квартира",
    description: "Воздушное пространство с округлыми формами, скрытым светом и натуральными материалами.",
    works: ["концепция", "визуализации", "подбор материалов", "авторский надзор"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "4 комнаты", style: "soft contemporary", palette: "камень, лен, бронза" },
  },
  {
    slug: "pine-house",
    title: "Дом среди сосен",
    city: "Московская область",
    area: "240 м²",
    year: "2025",
    type: "Загородный дом",
    description: "Дом с панорамным остеклением, камином и интерьером, который продолжает ландшафт за окном.",
    works: ["проект под ключ", "комплектация", "декорирование", "сопровождение"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "2 этажа", style: "natural luxury", palette: "дерево, графит, шерсть" },
  },
  {
    slug: "urban-silence",
    title: "Городская тишина",
    city: "Москва",
    area: "71 м²",
    year: "2024",
    type: "Апартаменты",
    description: "Компактные апартаменты с гостиничной логикой и большим количеством скрытого хранения.",
    works: ["планировка", "технический проект", "визуализации", "свет"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "2 комнаты", style: "urban calm", palette: "кофе, бетон, стекло" },
  },
  {
    slug: "warm-geometry",
    title: "Теплая геометрия",
    city: "Казань",
    area: "110 м²",
    year: "2024",
    type: "Квартира",
    description: "Проект с выразительной геометрией панелей, мягкой мебелью и продуманными сценариями света.",
    works: ["концепция", "документация", "подбор мебели", "комплектация"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "3 комнаты", style: "contemporary", palette: "орех, тауп, латунь" },
  },
  {
    slug: "monochrome-office",
    title: "Monochrome Office",
    city: "Москва",
    area: "180 м²",
    year: "2023",
    type: "Коммерческий интерьер",
    description: "Сдержанный офис для команды, где приватные зоны, переговорные и lounge объединены одной пластикой.",
    works: ["бренд-среда", "планировка", "свет", "рабочая документация"],
    cover: "/images/interior-placeholder.svg",
    images: gallery(),
    layout: "/images/plan-placeholder.svg",
    characteristics: { rooms: "open space + 5 кабинетов", style: "monochrome", palette: "графит, стекло, текстиль" },
  },
];
